# Generated by Django 5.0.3 on 2024-06-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
