# Generated by Django 5.0.3 on 2024-06-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_folder_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
